// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/assets": {
            "get": {
                "description": "Retrieve all assets in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List all assets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/asset_controllers.AssetsResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve assets",
                        "schema": {
                            "$ref": "#/definitions/asset_controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "asset_controllers.AssetsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AsLand"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "asset_controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.AsLand": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "cutax_land_id": {
                    "type": "string"
                },
                "deed_no": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "estimated_price": {
                    "type": "number"
                },
                "estimated_price_by_treasury": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "is_estimated_by_treasury": {
                    "type": "boolean"
                },
                "land_district_id": {
                    "type": "integer"
                },
                "land_no": {
                    "type": "string"
                },
                "land_space_ngan": {
                    "type": "number"
                },
                "land_space_rai": {
                    "type": "number"
                },
                "land_space_sub_wa": {
                    "type": "number"
                },
                "land_space_wa": {
                    "type": "number"
                },
                "land_sub_district_id": {
                    "type": "integer"
                },
                "land_zone": {
                    "type": "string"
                },
                "map_geometry": {
                    "type": "string"
                },
                "map_lat": {
                    "type": "string"
                },
                "map_long": {
                    "type": "string"
                },
                "muni_code": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "parcel_no": {
                    "type": "string"
                },
                "parcel_type": {
                    "type": "integer"
                },
                "road": {
                    "type": "string"
                },
                "source_dt": {
                    "type": "string"
                },
                "special_usetax_type": {
                    "type": "string"
                },
                "survey_no": {
                    "type": "string"
                },
                "sync_id": {
                    "type": "string"
                },
                "tax_year": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                },
                "utm_map1": {
                    "type": "string"
                },
                "utm_map2": {
                    "type": "string"
                },
                "utm_map3": {
                    "type": "string"
                },
                "utm_map4": {
                    "type": "string"
                },
                "utm_scale": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
