definitions:
  response.Response:
    properties:
      data: {}
      error:
        example: Detailed error description
        type: string
      message:
        example: Operation successful
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Citizen System API
  version: "1.0"
paths:
  /api/v1/assets:
    get:
      consumes:
      - application/json
      description: Get a list of all assets with optional filtering
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: List all assets
      tags:
      - assets
  /api/v1/assets/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve an asset by its ID
      parameters:
      - description: Asset ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get asset by ID
      tags:
      - assets
  /api/v1/assets/get_asset_by_user_id/{user_id}:
    get:
      consumes:
      - application/json
      description: Get all asset with user id
      parameters:
      - description: User ID (UUID)
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get all asset
      tags:
      - assets
  /api/v1/dev_tools/gen_model/{table_name}:
    get:
      consumes:
      - application/json
      description: Generate model
      parameters:
      - description: The name of the table to generate model for
        in: path
        name: table_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Generate model
      tags:
      - dev_tools
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
